import type { Metadata } from "next";
import { Pacifico, Delius_Swash_Caps } from "next/font/google";
import "./globals.css";

const pacifico = Pacifico({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-pacifico",
});

const deliusswashcaps = Delius_Swash_Caps({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-delius-swash-caps",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${deliusswashcaps.variable} ${pacifico.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
